theme: jekyll-theme-minimal
title: [Mechanically robust lattices inspired by deep-sea glass sponges]
description: [This contains the data and code for the publication in Nature Materials.]
google_analytics: [UA-50387353-16]